import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "sm": "640px",
        "md": "768px",
        "lg": "1024px",
        "xl": "1280px",
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Open Sans', 'system-ui', 'sans-serif'],
        heading: ['Montserrat', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(var(--primary) / 0.05)",
          100: "hsl(var(--primary) / 0.1)",
          200: "hsl(var(--primary) / 0.2)",
          300: "hsl(var(--primary) / 0.3)",
          400: "hsl(var(--primary) / 0.4)",
          500: "hsl(var(--primary) / 0.5)",
          600: "hsl(var(--primary) / 0.6)",
          700: "hsl(var(--primary) / 0.7)",
          800: "hsl(var(--primary) / 0.8)",
          900: "hsl(var(--primary) / 0.9)",
          950: "hsl(var(--primary) / 0.95)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          50: "hsl(var(--secondary) / 0.05)",
          100: "hsl(var(--secondary) / 0.1)",
          200: "hsl(var(--secondary) / 0.2)",
          300: "hsl(var(--secondary) / 0.3)",
          400: "hsl(var(--secondary) / 0.4)",
          500: "hsl(var(--secondary) / 0.5)",
          600: "hsl(var(--secondary) / 0.6)",
          700: "hsl(var(--secondary) / 0.7)",
          800: "hsl(var(--secondary) / 0.8)",
          900: "hsl(var(--secondary) / 0.9)",
          950: "hsl(var(--secondary) / 0.95)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          50: "hsl(var(--destructive) / 0.05)",
          100: "hsl(var(--destructive) / 0.1)",
          200: "hsl(var(--destructive) / 0.2)",
          300: "hsl(var(--destructive) / 0.3)",
          400: "hsl(var(--destructive) / 0.4)",
          500: "hsl(var(--destructive) / 0.5)",
          600: "hsl(var(--destructive) / 0.6)",
          700: "hsl(var(--destructive) / 0.7)",
          800: "hsl(var(--destructive) / 0.8)",
          900: "hsl(var(--destructive) / 0.9)",
          950: "hsl(var(--destructive) / 0.95)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
          50: "hsl(var(--muted) / 0.05)",
          100: "hsl(var(--muted) / 0.1)",
          200: "hsl(var(--muted) / 0.2)",
          300: "hsl(var(--muted) / 0.3)",
          400: "hsl(var(--muted) / 0.4)",
          500: "hsl(var(--muted) / 0.5)",
          600: "hsl(var(--muted) / 0.6)",
          700: "hsl(var(--muted) / 0.7)",
          800: "hsl(var(--muted) / 0.8)",
          900: "hsl(var(--muted) / 0.9)",
          950: "hsl(var(--muted) / 0.95)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          50: "hsl(var(--accent) / 0.05)",
          100: "hsl(var(--accent) / 0.1)",
          200: "hsl(var(--accent) / 0.2)",
          300: "hsl(var(--accent) / 0.3)",
          400: "hsl(var(--accent) / 0.4)",
          500: "hsl(var(--accent) / 0.5)",
          600: "hsl(var(--accent) / 0.6)",
          700: "hsl(var(--accent) / 0.7)",
          800: "hsl(var(--accent) / 0.8)",
          900: "hsl(var(--accent) / 0.9)",
          950: "hsl(var(--accent) / 0.95)",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          50: "hsl(var(--success) / 0.05)",
          100: "hsl(var(--success) / 0.1)",
          200: "hsl(var(--success) / 0.2)",
          300: "hsl(var(--success) / 0.3)",
          400: "hsl(var(--success) / 0.4)",
          500: "hsl(var(--success) / 0.5)",
          600: "hsl(var(--success) / 0.6)",
          700: "hsl(var(--success) / 0.7)",
          800: "hsl(var(--success) / 0.8)",
          900: "hsl(var(--success) / 0.9)",
          950: "hsl(var(--success) / 0.95)",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          50: "hsl(var(--warning) / 0.05)",
          100: "hsl(var(--warning) / 0.1)",
          200: "hsl(var(--warning) / 0.2)",
          300: "hsl(var(--warning) / 0.3)",
          400: "hsl(var(--warning) / 0.4)",
          500: "hsl(var(--warning) / 0.5)",
          600: "hsl(var(--warning) / 0.6)",
          700: "hsl(var(--warning) / 0.7)",
          800: "hsl(var(--warning) / 0.8)",
          900: "hsl(var(--warning) / 0.9)",
          950: "hsl(var(--warning) / 0.95)",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
          50: "hsl(var(--info) / 0.05)",
          100: "hsl(var(--info) / 0.1)",
          200: "hsl(var(--info) / 0.2)",
          300: "hsl(var(--info) / 0.3)",
          400: "hsl(var(--info) / 0.4)",
          500: "hsl(var(--info) / 0.5)",
          600: "hsl(var(--info) / 0.6)",
          700: "hsl(var(--info) / 0.7)",
          800: "hsl(var(--info) / 0.8)",
          900: "hsl(var(--info) / 0.9)",
          950: "hsl(var(--info) / 0.95)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
        "3xl": "calc(var(--radius) + 12px)",
        "4xl": "calc(var(--radius) + 16px)",
        full: "9999px",
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        'dark-lg': '0 10px 15px -3px rgba(0, 0, 0, 0.5), 0 4px 6px -2px rgba(0, 0, 0, 0.3)',
        'glow': 'var(--shadow-glow)',
        'glow-accent': 'var(--shadow-glow-accent)',
        'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)',
        'inner-md': 'inset 0 4px 6px 0 rgba(0, 0, 0, 0.1)',
        'inner-lg': 'inset 0 8px 10px -4px rgba(0, 0, 0, 0.1)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-dark': 'linear-gradient(to right, #0A0E16, #111827)',
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-secondary': 'var(--gradient-secondary)',
        'gradient-accent': 'var(--gradient-accent)',
        'gradient-success': 'var(--gradient-success)',
        'gradient-warning': 'var(--gradient-warning)',
        'gradient-info': 'var(--gradient-info)',
        'gradient-destructive': 'var(--gradient-destructive)',
        'gradient-background': 'var(--gradient-background)',
        'gradient-card': 'var(--gradient-card)',
        'gradient-glass': 'var(--gradient-glass)',
        'gradient-frost': 'var(--gradient-frost)',
        'noise': 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.65\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\'/%3E%3C/svg%3E")',
      },
      spacing: {
        '4.5': '1.125rem',
        '5.5': '1.375rem',
        '6.5': '1.625rem',
        '7.5': '1.875rem',
        '8.5': '2.125rem',
        '9.5': '2.375rem',
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
        'width': 'width',
        'size': 'width, height',
      },
      transitionTimingFunction: {
        'bounce-start': 'cubic-bezier(0.17, 0.67, 0.83, 0.67)',
        'bounce-end': 'cubic-bezier(0.17, 0.67, 0.17, 1)',
        'emphasis': 'cubic-bezier(0.18, 1.25, 0.4, 1)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(-10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-out": {
          from: { opacity: "1", transform: "translateY(0)" },
          to: { opacity: "0", transform: "translateY(10px)" },
        },
        "slide-in": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-out": {
          from: { transform: "translateX(0)" },
          to: { transform: "translateX(100%)" },
        },
        "slide-up": {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
        "slide-down": {
          from: { transform: "translateY(0)" },
          to: { transform: "translateY(100%)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "scale-out": {
          from: { opacity: "1", transform: "scale(1)" },
          to: { opacity: "0", transform: "scale(0.95)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "bounce-light": {
          "0%, 100%": { transform: "translateY(0)", animationTimingFunction: "cubic-bezier(0.8, 0, 1, 1)" },
          "50%": { transform: "translateY(-15%)", animationTimingFunction: "cubic-bezier(0, 0, 0.2, 1)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-out": "fade-out 0.3s ease-in",
        "slide-in": "slide-in 0.3s ease-out",
        "slide-out": "slide-out 0.3s ease-in",
        "slide-up": "slide-up 0.3s ease-out",
        "slide-down": "slide-down 0.3s ease-in",
        "scale-in": "scale-in 0.2s ease-out",
        "scale-out": "scale-out 0.2s ease-in",
        "float": "float 3s ease-in-out infinite",
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "spin-slow": "spin-slow 3s linear infinite",
        "bounce-light": "bounce-light 2s infinite",
      },
      backdropBlur: {
        xs: '2px',
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: '65ch',
            color: 'hsl(var(--foreground))',
            a: {
              color: 'hsl(var(--primary))',
              '&:hover': {
                color: 'hsl(var(--primary) / 0.8)',
              },
            },
            strong: {
              color: 'hsl(var(--foreground))',
            },
            h1: {
              color: 'hsl(var(--foreground))',
              fontFamily: 'var(--font-heading)',
            },
            h2: {
              color: 'hsl(var(--foreground))',
              fontFamily: 'var(--font-heading)',
            },
            h3: {
              color: 'hsl(var(--foreground))',
              fontFamily: 'var(--font-heading)',
            },
            h4: {
              color: 'hsl(var(--foreground))',
              fontFamily: 'var(--font-heading)',
            },
            code: {
              color: 'hsl(var(--foreground))',
              backgroundColor: 'hsl(var(--muted))',
              borderRadius: '0.25rem',
              paddingLeft: '0.25rem',
              paddingRight: '0.25rem',
              paddingTop: '0.125rem',
              paddingBottom: '0.125rem',
              fontFamily: 'var(--font-mono)',
            },
            pre: {
              backgroundColor: 'hsl(var(--muted))',
              borderRadius: 'var(--radius)',
              padding: '1rem',
              fontFamily: 'var(--font-mono)',
            },
            blockquote: {
              color: 'hsl(var(--muted-foreground))',
              borderLeftColor: 'hsl(var(--border))',
            },
            hr: {
              borderColor: 'hsl(var(--border))',
            },
            figcaption: {
              color: 'hsl(var(--muted-foreground))',
            },
            dt: {
              color: 'hsl(var(--foreground))',
            },
            dd: {
              marginLeft: '1.5rem',
            },
            li: {
              marginTop: '0.25rem',
              marginBottom: '0.25rem',
            },
            'ol > li::marker': {
              color: 'hsl(var(--muted-foreground))',
            },
            'ul > li::marker': {
              color: 'hsl(var(--muted-foreground))',
            },
            'ul > li > p': {
              marginTop: '0.25rem',
              marginBottom: '0.25rem',
            },
            'ol > li > p': {
              marginTop: '0.25rem',
              marginBottom: '0.25rem',
            },
          },
        },
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms')({
      strategy: 'class',
    }),
    require('@tailwindcss/aspect-ratio'),
  ],
} satisfies Config;
