// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbxoxxgpcuqpwfalmbpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhieG94eGdwY3VxcHdmYWxtYnBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODQ5OTEsImV4cCI6MjA2MDk2MDk5MX0.22plPtuuSg8NoUskMQwVPqAMcMHuoTior6n4d0GVwNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);